# Generated by Django 3.1.1 on 2020-09-12 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20200912_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='pub_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
