# Generated by Django 3.1.1 on 2020-09-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_dish_pub_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
